### ISSUE TITLE
Create a domestic ontology/integrate an existing one 

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#6]
Worth 10 points.

We need an ontology that at least:

* models semantic object knowledge (e.g. geometric object properties, contexts in which the object could be used, etc.)
* associates geometric points to semantic locations

**Comment by alex-mitrevski** [comment]
The groundwork for this has been laid with PR https://github.com/b-it-bots/mas_domestic_robotics/pull/63; the integration of the ontology with the rest of the code base is ongoing work, but the issue doesn't need to remain open at this point.

**Comment by alex-mitrevski** [comment]
Just for the record, I've moved the ontology and the query interface (as well as the knowledge base interface discussed in issue https://github.com/b-it-bots/mas_domestic_robotics/issues/86) to a new repository: https://github.com/b-it-bots/mas_knowledge_base

There are two main reasons for this:
* This is already a relatively large piece of code and is better of independent since it could also be reusable by other applications
* Dependency management: `mas_execution_manager` and `mas_domestic_robotics` both depend on the knowledge base, so I didn't want to have a circular dependency between the two; this way, both of them depend on a separate repository
